from mass_loss import calculate_mass_loss_rate
from wind_collimation import calculate_wind_collimation
from wind_velocity import calculate_wind_velocity 
from wind_temperature import calculate_wind_temperature

