from mass_loss import calculate_mass_loss_rate
from wind_collimation import get_collimation_degree
from velocity_gradient import compute_velocity_gradient
from wind_temperature import calculate_wind_temperature
